name: Update GitHub Activity README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

# Keeps the write permissions you successfully fixed!
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity
    
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "ACTIVITY"
          feed_list: "https://github.com/omkharade318.atom"
          max_post_count: 5
